### ISSUE TITLE
PDF to mindmap?

### ISSUE THREAD

**Issue by oldschoola** [robertZaufall/mindmanager_ai#1]
Is it possible to use this with a pdf?

I see it says "Create a map based on external text data"
How would i covert a pdf to the format this can use?

**Comment by robertZaufall** [comment]
I'm working on this. Typically, this seems to be a standard RAG use case, and there are several frameworks available to accomplish this. The hottest topic regarding RAG at the moment is GraphRAG, which involves RAG in conjunction with knowledge graphs. This can be done, for example, using LlamaIndex/LangChain in combination with Neo4j.

**Comment by robertZaufall** [comment]
I implemented a first version to summarize a PDF-file and genrate a mindmap from the summary.  
The PDF is converted to markdown first using the `pymupdf4llm` library.

**Comment by robertZaufall** [comment]
I implemented another way using native multimodal capabilities of (VertexAI / Gemini) models to use PDF files.
